# Generated by Django 2.2.7 on 2020-04-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='suspectadress',
        ),
        migrations.RemoveField(
            model_name='report',
            name='suspectm',
        ),
        migrations.RemoveField(
            model_name='report',
            name='suspectname',
        ),
        migrations.AddField(
            model_name='report',
            name='informer_mobile',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='report',
            name='informer_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='report',
            name='suspect_adress',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='report',
            name='suspect_mobile',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='report',
            name='suspect_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
