# Generated by Django 2.2.7 on 2020-04-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('casesd', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=300)),
                ('case', models.CharField(default='', max_length=300)),
                ('activecase', models.CharField(default='', max_length=300)),
                ('death1', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=300)),
                ('totalcase', models.CharField(default='', max_length=300)),
                ('active', models.CharField(default='', max_length=300)),
                ('death', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='mobile',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='report',
            name='suspectadress',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='suspectm',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='suspectname',
            field=models.CharField(default='', max_length=300),
        ),
    ]
