# Generated by Django 2.2.7 on 2020-04-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_auto_20200411_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='', max_length=300)),
                ('country_case', models.CharField(default='', max_length=300)),
                ('country_active_case', models.CharField(default='', max_length=300)),
                ('country_recovered_case', models.CharField(default='', max_length=300)),
                ('country_death_case', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='headIndia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_india_case', models.CharField(default='', max_length=300)),
                ('active_india_case', models.CharField(default='', max_length=300)),
                ('india_death_case', models.CharField(default='', max_length=300)),
                ('recovered_india_case', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='headWorld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_world_case', models.CharField(default='', max_length=300)),
                ('active_world_case', models.CharField(default='', max_length=300)),
                ('world_death_case', models.CharField(default='', max_length=300)),
                ('recovered_world_case', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='World',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='casesd',
            new_name='district_cases',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='district_name',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='informer_name',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='suspectadress',
            new_name='suspect_adress',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='suspectname',
            new_name='suspect_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='activecase',
            new_name='state_active_case',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='case',
            new_name='state_case',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='death1',
            new_name='state_death_case',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='state_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='report',
            name='suspectm',
        ),
        migrations.AddField(
            model_name='report',
            name='informer_mobile',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='report',
            name='suspect_mobile',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='state',
            name='state_recovered_case',
            field=models.CharField(default='', max_length=300),
        ),
    ]
