# Generated by Django 2.2.7 on 2020-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mobile', models.IntegerField()),
                ('suspectm', models.IntegerField()),
                ('suspectname', models.CharField(max_length=300)),
                ('suspectadress', models.CharField(max_length=1000)),
            ],
        ),
    ]
